[2024-05-25T05:37:25.636+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:37:25.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T05:37:25.639+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:37:25.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:37:26.419+0000] {processor.py:840} INFO - DAG(s) 'extenso_assignment' retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:37:26.650+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:37:26.649+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-25T05:37:26.677+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:37:26.677+0000] {dag.py:3954} INFO - Setting next_dagrun for extenso_assignment to None, run_after=None
[2024-05-25T05:37:26.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.089 seconds
[2024-05-25T05:37:56.872+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:37:56.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T05:37:56.874+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:37:56.874+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:37:57.618+0000] {processor.py:840} INFO - DAG(s) 'extenso_assignment' retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:37:57.658+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:37:57.657+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-25T05:37:57.768+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:37:57.768+0000] {dag.py:3954} INFO - Setting next_dagrun for extenso_assignment to None, run_after=None
[2024-05-25T05:37:57.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.969 seconds
[2024-05-25T05:38:28.849+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:38:28.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T05:38:28.861+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:38:28.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:38:29.950+0000] {processor.py:840} INFO - DAG(s) 'extenso_assignment' retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T05:38:29.973+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:38:29.973+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-25T05:38:30.052+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:38:30.052+0000] {dag.py:3954} INFO - Setting next_dagrun for extenso_assignment to None, run_after=None
[2024-05-25T05:38:30.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.319 seconds
[2024-05-25T10:42:35.694+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:42:35.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:42:35.712+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:42:35.702+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:42:58.139+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:42:57.747+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:42:58.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:42:58.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 23.056 seconds
[2024-05-25T10:43:30.373+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:43:30.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:43:30.406+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:43:30.405+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:43:32.776+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:43:32.761+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:43:32.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:43:32.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 2.484 seconds
[2024-05-25T10:44:03.270+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:44:03.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:44:03.273+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:44:03.272+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:44:03.908+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:44:03.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:44:03.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:44:03.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.676 seconds
[2024-05-25T10:44:34.889+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:44:34.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:44:34.893+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:44:34.892+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:44:38.645+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:44:38.635+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:44:38.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:44:38.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 3.810 seconds
[2024-05-25T10:45:09.264+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:45:09.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:45:09.270+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:45:09.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:45:10.974+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:45:10.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:45:10.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:45:11.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.813 seconds
[2024-05-25T10:45:41.635+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:45:41.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:45:41.643+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:45:41.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:45:43.217+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:45:43.208+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:45:43.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:45:43.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.625 seconds
[2024-05-25T10:46:14.281+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:46:14.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:46:14.292+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:46:14.289+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:46:15.274+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:46:15.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:46:15.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:46:15.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.163 seconds
[2024-05-25T10:46:45.809+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:46:45.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:46:45.817+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:46:45.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:46:48.258+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:46:48.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:46:48.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:46:48.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 2.500 seconds
[2024-05-25T10:47:18.943+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:47:18.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:47:18.955+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:47:18.952+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:47:20.681+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:47:20.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:47:20.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:47:20.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.815 seconds
[2024-05-25T10:47:51.468+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:47:51.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:47:51.471+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:47:51.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:47:52.315+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:47:52.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:47:52.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:47:52.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.883 seconds
[2024-05-25T10:48:22.525+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:48:22.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:48:22.528+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:48:22.528+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:48:23.443+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:48:23.429+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:48:23.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:48:23.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.959 seconds
[2024-05-25T10:48:54.120+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:48:54.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:48:54.123+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:48:54.123+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:48:54.942+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:48:54.923+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:48:54.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:48:54.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.867 seconds
[2024-05-25T10:49:28.012+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:49:28.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:49:28.030+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:49:28.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:49:29.409+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:49:29.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:49:29.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:49:29.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.463 seconds
[2024-05-25T10:49:59.868+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:49:59.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:49:59.870+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:49:59.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:50:00.830+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:50:00.823+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:50:00.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:50:00.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.001 seconds
[2024-05-25T10:50:31.137+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:50:31.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:50:31.140+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:50:31.139+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:50:32.074+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:50:32.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:50:32.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:50:32.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.985 seconds
[2024-05-25T10:51:04.589+0000] {processor.py:161} INFO - Started process (PID=547) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:51:04.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:51:04.592+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:51:04.592+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:51:05.483+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:51:05.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:51:05.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:51:05.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 0.937 seconds
[2024-05-25T10:51:35.993+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:51:35.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:51:35.998+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:51:35.996+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:51:37.048+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:51:37.039+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:51:37.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:51:37.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.094 seconds
[2024-05-25T10:52:07.516+0000] {processor.py:161} INFO - Started process (PID=595) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:52:07.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:52:07.534+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:52:07.533+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:52:08.882+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:52:08.872+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:52:08.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:52:08.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.418 seconds
[2024-05-25T10:52:39.948+0000] {processor.py:161} INFO - Started process (PID=625) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:52:39.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:52:39.952+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:52:39.951+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:52:40.913+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:52:40.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:52:40.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:52:41.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 1.103 seconds
[2024-05-25T10:53:13.567+0000] {processor.py:161} INFO - Started process (PID=650) to work on /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:53:13.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dump_load_dag.py for tasks to queue
[2024-05-25T10:53:13.586+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:53:13.580+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:53:16.606+0000] {logging_mixin.py:188} INFO - [2024-05-25T10:53:16.548+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dump_load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dump_load_dag.py", line 7, in <module>
    from preprocess_combination import final_entity_matching
  File "/opt/airflow/dags/preprocess_combination.py", line 5, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
ModuleNotFoundError: No module named 'sklearn'
[2024-05-25T10:53:16.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dump_load_dag.py
[2024-05-25T10:53:16.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dump_load_dag.py took 3.190 seconds
